"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

# Explicit loading of .env file if it exists
try:
    from dotenv import load_dotenv

    env_path = Path(__file__).resolve().parent.parent / ".env"
    if env_path.exists():
        load_dotenv(env_path)
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-+m3q+&9eni)-43c#$ul*y171gh=gpixqesj9bgu8zkc#ps#g%_"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,api.sentx.ai,192.168.1.48").split(",")

CSRF_TRUSTED_ORIGINS = ['https://api.sentx.ai']
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # Для блэклиста refresh токенов
    "djoser",
    "social_django",
    "drf_spectacular",
    "corsheaders",
    "apps.users",
    "apps.payments",
    "apps.ChatSessions",
    "apps.messages",
    "apps.feedbacks",
    "apps.attachedFiles",
    "apps.usageLimits",
    "apps.anonymousUsageLimits",
    "apps.chat",
    "apps.admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Moved to top for proper CORS handling
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "server" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {"default": dj_database_url.config(default=DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    BASE_DIR / "server" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'apps.chat.renderers.SSERenderer',  # Custom renderer for SSE
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SentX API",
    "DESCRIPTION": "SentX is a generative artificial intelligence chatbot.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api",
    "SECURITY": [{"bearerAuth": []}],
    "SECURITY_DEFINITIONS": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        },
    },
}


AUTH_USER_MODEL = "users.User"

DJOSER = {
    # Email settings
    "EMAIL_FRONTEND_PROTOCOL": "https",
    "EMAIL_FRONTEND_DOMAIN": "sentx.ai",
    "EMAIL_FRONTEND_SITE_NAME": "SentX",
    "PASSWORD_RESET_CONFIRM_URL": "#/password/reset/confirm/{uid}/{token}",
    
    # Authentication
    "LOGIN_FIELD": "email",
    
    # Email confirmations
    "SEND_ACTIVATION_EMAIL": False,
    "SEND_CONFIRMATION_EMAIL": False,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": False,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": False,
    
    # Password settings
    "USER_CREATE_PASSWORD_RETYPE": True,  # Требовать re_password при регистрации
    "SET_PASSWORD_RETYPE": True,  # Требовать подтверждение при смене пароля
    "LOGOUT_ON_PASSWORD_CHANGE": False,  # Не разлогинивать при смене пароля
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": False,  # Не показывать, что email не найден
    
    # User visibility
    "HIDE_USERS": True,  # Скрыть список пользователей от обычных юзеров
    
    # Permissions - строгий контроль доступа
    "PERMISSIONS": {
        "user_list": ["rest_framework.permissions.IsAdminUser"],  # Только admin видит список
        "user": ["rest_framework.permissions.IsAuthenticated"],  # Только свой профиль
        "user_create": ["rest_framework.permissions.AllowAny"],  # Регистрация для всех
        "user_delete": ["rest_framework.permissions.IsAuthenticated"],  # Удаление своего аккаунта
        "set_password": ["rest_framework.permissions.IsAuthenticated"],  # Смена пароля
        "username_reset": ["rest_framework.permissions.AllowAny"],
        "username_reset_confirm": ["rest_framework.permissions.AllowAny"],
        "set_username": ["rest_framework.permissions.IsAuthenticated"],
        "password_reset": ["rest_framework.permissions.AllowAny"],
        "password_reset_confirm": ["rest_framework.permissions.AllowAny"],
        "activation": ["rest_framework.permissions.AllowAny"],
        "token_create": ["rest_framework.permissions.AllowAny"],
        "token_destroy": ["rest_framework.permissions.IsAuthenticated"],
    },
    
    # Serializers
    "SERIALIZERS": {
        "user": "apps.users.serializers.UserSerializer",  # Для GET /users/me/
        "current_user": "apps.users.serializers.UserSerializer",  # Для текущего юзера
        "user_create": "apps.users.serializers.UserCreateSerializer",  # Для POST /users/
        "user_delete": "djoser.serializers.UserDeleteSerializer",
    },
}

# Stripe Settings
STRIPE_PUBLISHABLE_KEY = os.environ.get(
    "STRIPE_PUBLISHABLE_KEY", "pk_test_your_test_key"
)
STRIPE_API_KEY = os.environ.get("STRIPE_API_KEY", "sk_test_your_test_key")
STRIPE_WEBHOOK_SECRET = os.environ.get(
    "STRIPE_WEBHOOK_SECRET", "whsec_your_webhook_secret"
)

# OpenAI / SentX LLM Settings
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://s-api-sv-0028.ngrok.app/v1")
OPENAI_DEFAULT_MODEL = os.environ.get("OPENAI_DEFAULT_MODEL", "sentx_4.0")

# SentX API Key (используется для модели sentx)
SENTX_SECRET_KEY = os.environ.get("SENTX_SECRET_KEY", "")

# Abfuscator Settings
ABFUSCATOR_ID_KEY = os.environ.get("ABFUSCATOR_ID_KEY", "super_secret_key")

# Media files (uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SIMPLE_JWT = {
    # Token lifetimes
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),  # 1 час - короткий access token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # 30 дней - длинный refresh token
    
    # Token rotation and blacklisting
    "ROTATE_REFRESH_TOKENS": True,  # Ротация refresh токенов при обновлении
    "BLACKLIST_AFTER_ROTATION": True,  # Блэклист старых refresh токенов
    "UPDATE_LAST_LOGIN": True,  # Обновление last_login при получении токена
    
    # Algorithm and signing
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    
    # Auth header configuration
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    
    # User identification in token
    "USER_ID_FIELD": "id",  # Поле в User model для идентификации
    "USER_ID_CLAIM": "user_id",  # Название claim в JWT payload
    
    # Token types
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    
    # JWT ID
    "JTI_CLAIM": "jti",
    
    # Sliding tokens (not used, but configured for clarity)
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

SOCIAL_AUTH_JSONFIELD_ENABLED = True

# Social Auth Settings
AUTHENTICATION_BACKENDS = (
    "apps.users.backends.CustomGoogleOAuth2",
    "apps.users.backends.CustomTwitterOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)

# Google OAuth2 Settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get("GOOGLE_OAUTH2_KEY", "")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get("GOOGLE_OAUTH2_SECRET", "")
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_PKCE = True
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "openid",
    "email",
    "profile",
]
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    "access_type": "offline",
}
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API = False
SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ["email", "name", "picture"]
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = []
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS = []

# Twitter OAuth2 Settings
SOCIAL_AUTH_TWITTER_OAUTH2_KEY = os.environ.get("TWITTER_OAUTH2_KEY", "")
SOCIAL_AUTH_TWITTER_OAUTH2_SECRET = os.environ.get("TWITTER_OAUTH2_SECRET", "")
SOCIAL_AUTH_TWITTER_OAUTH2_PKCE_CODE_CHALLENGE_METHOD = "S256"
SOCIAL_AUTH_TWITTER_OAUTH2_SCOPE = ["tweet.read", "users.read", "offline.access"]

# Social Auth URLs
SOCIAL_AUTH_LOGIN_REDIRECT_URL = os.environ.get(
    "SOCIAL_AUTH_LOGIN_REDIRECT_URL",
    "https://sentx.ai/auth/google/callback"
    if not DEBUG
    else "http://localhost:5173/auth/google/callback",
)
SOCIAL_AUTH_LOGIN_ERROR_URL = os.environ.get(
    "SOCIAL_AUTH_LOGIN_ERROR_URL",
    "https://sentx.ai/auth/error" if not DEBUG else "http://localhost:5173/auth/error",
)
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Allowed redirect URIs for frontend
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = os.environ.get(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI",
    "https://sentx.ai/auth/google/callback"
    if not DEBUG
    else "http://localhost:5173/auth/google/callback",
)

# CORS settings for frontend
CORS_ALLOWED_ORIGINS = [
    "https://sentx.ai",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# In development mode, we allow all origins
# CORS_ALLOW_ALL_ORIGINS = DEBUG  # Commented out to support credentials (wildcard '*' conflicts with credentials)
CORS_ALLOW_ALL_ORIGINS = False

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for SSE
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-fingerprint-hash',  # Custom header for fingerprint identification
    'cache-control',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'cache-control',
    'x-accel-buffering',
]

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "sentx-admin-cache",
        "TIMEOUT": 300,  # 5 minutes default
        "OPTIONS": {
            "MAX_ENTRIES": 1000
        }
    }
}

# Logging settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "social_core": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        "apps.users": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
        "apps.users.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "apps.admin": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": True,
        },
    },
}

# Email settings
EMAIL_HOST = "smtp.yandex.ru"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "develop@kuki.agency")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "cycraw-fifhu5-Waswaj")

EMAIL_SERVER = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

# Additional security settings for OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_UNIQUE_USER_ID = True
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ["email"]

# Social authentication pipeline
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)
